//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKit.h>
#import "HBCompose/HBComposeViewController.h"

@interface WCTimeLineViewController : UIViewController <HBComposeViewControllerDelegate>

- (void)openWriteTextViewController;
- (void)showMessageList;
- (void)showImagePicker:(long long)arg1;
- (void)openCommitViewController:(_Bool)arg1 arrImage:(id)arg2;

@end

